; PlatformIO Project Configuration File
; Conveyor Sorting System with Hybrid Barcode + UHF RFID
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32doit-devkit-v1]
platform = espressif32@6.11.0  ; More stable on Windows
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps = 
    mobizt/Firebase ESP32 Client@^4.4.14
    madhephaestus/ESP32Servo@^1.2.1
    tzapu/WiFiManager@^2.0.17
    bblanchon/ArduinoJson@^7.0.4

build_type = debug
build_flags = 
    -DCORE_DEBUG_LEVEL=5
    -DBOARD_HAS_PSRAM=0

; Add this to fix Windows toolchain path issues
build_unflags = -Werror

monitor_filters = 
    esp32_exception_decoder
    time

board_build.partitions = huge_app.csv
test_framework = unity